# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
   include:
     - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'e69ee632-eb4a-49dd-b82b-ab040d48dd81'
  imageRepository: 'projectdevops-vote'
  containerRegistry: 'azuredevopsvotingapp.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildNumber)'

pool:
  name: 'devopsagent'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: Push
  displayName:  Push
  jobs:
  - job: Push
    steps:
    - task: Docker@2
      displayName: Push an image to repository
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'
